#!/bin/bash

# these libs need to be compiled in order

wmake libso normalMotionSlipBasePointPatchField
wmake libso normalMotionSlipPointPatchField
wmake libso codedNormalMotionSlipPointPatchField
wmake libso normalMotionSlipFvPatchField
wmake libso codedNormalMotionSlipFvPatchField
