#!/bin/bash

echo "Cleaning all libraries"
for d in */ ; do
  if [ -d ${d}/Make ]; then
    wclean $d
  fi
  if [ -f ${d}/Allwmake ]; then
    echo "Making library $d"
    pushd $d
    ./Allwclean
    popd
  fi
done

