#!/bin/bash

for d in */ ; do
  if [ -d ${d}/Make ]; then
    echo "Making library $d"
    wmake libso $d
  fi
  if [ -f ${d}/Allwmake ]; then
    echo "Making library $d"
    pushd $d
    ./Allwmake
    popd
  fi
done
