#!/bin/bash

echo "Clean everything"
rm -rf ../lnInclude                   # remove links
for d in */ ; do
  if [ -d ${d}/Make ]; then
    wclean $d
  elif [ -f ${d}/Allclean ]; then
    pushd $d
    ./Allclean
    popd
  fi
done

