#!/bin/bash

echo "Clean everything"
rm -r ../lnInclude                      # Clean links
for d in */ ; do
  if [ -d ${d}/Make ]; then
    wclean $d
  elif [ -f ${d}/Allwmake ]; then
    pushd $d
    ./Allwclean
    popd
  fi
done

