#!/bin/bash

echo "Make everything"
./mkInclude                       # make links
for d in */ ; do
  if [ -d ${d}/Make ]; then
    wmake $d
  elif [ -f ${d}/Allwmake ]; then
    pushd $d
    ./Allwmake
    popd
  fi
done

