#!/bin/bash

#This script automatically created symlinks to desired OpenFOAM libraries in a target directory, lnInclude.

mkdir ../lnInclude

#Files to be linked
coupH=$(find -type f -name coupledPatchInterpolation.H)
  IFS=' ' read -a coupHArr <<< "$coupH"
CoupH=$(find -type f -name CoupledPatchInterpolation.H)
  IFS=' ' read -a CoupHArr <<< "$CoupH"
CoupC=$(find -type f -name CoupledPatchInterpolation.C)
  IFS=' ' read -a CoupCArr <<< "$CoupC"
steadyH=$(find -type f -name steadyStateControl.H)
  IFS=' ' read -a steadyHArr <<< "$steadyH"
meshH=$(find -type f -name meshRelax.H)
  IFS=' ' read -a meshArr <<< "$meshH" 
OFstrH=$(find -type f -name OFstreamMod.H)
  IFS=' ' read -a OFstrHArr <<< "$OFstrH" 
dissolM=$(find -type f -name dissolMotionPointPatchVectorField.H)
  IFS=' ' read -a dissolMArr <<< "$dissolM" 

locateArr=(${coupHArr[0]} ${CoupHArr[0]} ${CoupCArr[0]} ${steadyHArr[0]} ${meshArr[0]} ${OFstrH[0]} ${dissolM[0]})
for i in "${locateArr[@]}"
do  
  ln -st ../lnInclude/ $(pwd)/$i
done  
