#!/bin/bash
# Make symbolic links

curDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir -p ../lnInclude
cd ../lnInclude
for H in $(find $curDIR -type f -name "*.H"); do
    ln -sf $H
done

ln -sf $curDIR/coupledPatchInterpolation/CoupledPatchInterpolation.C
