#!/bin/bash
# Make symbolic links

curDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir -p ../lnInclude
cd ../lnInclude
#for H in $curDIR/*/*.H; do
for H in $(find $curDIR -type f -name "*.H"); do
    ln -s $H
done

ln -s $curDIR/coupledPatchInterpolation/CoupledPatchInterpolation.C
