#!/bin/bash

# these libs need to be compiled in order

wmake libso apertureAver
wmake libso volumeIntegrate
wmake libso volumeIntegrateZ
wmake libso field2tiff
#wmake libso volumeHisto

wmake libso curv

wmake libso patchValuesX
